services:
  web:
    build:
      context: .  # Вказує на поточну директорію, де розташований Dockerfile
      dockerfile: Dockerfile  # Вказує на Dockerfile для побудови образу
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - nginx
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SUPERUSER_EMAIL=portfoliocarbontool@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=portfoliocarbontoolPassword

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
