name: Deploy to AWS

on:
  push:
    branches:
      - master  # Тільки для пушів у гілку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@18.169.190.18 << 'EOF'
            cd /home/ec2-user/PortfolioCarbonTool
            git pull origin master  # Оновлюємо код з репозиторія
            
            # Білдимо новий образ Docker
            sudo docker build -t portfolio-carbon-tool . 
            
            # Зупиняємо старий контейнер
            sudo docker stop portfolio-carbon-tool || true
            
            # Оновлюємо контейнер без видалення, застосовуючи новий образ
            sudo docker start portfolio-carbon-tool || sudo docker run -d -p 8000:8000 --name portfolio-carbon-tool portfolio-carbon-tool
            
            # (Опціонально) Перезапуск контейнера з новими змінами
            sudo docker restart portfolio-carbon-tool
          EOF
