name: Deploy to AWS EC2

on:
  push:
    branches:
      - master  # Деплой буде запускатись при кожному пуші в гілку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ec2-user@18.169.190.18:/home/ec2-user/PortfolioCarbonTool

      - name: SSH to EC2 and run Docker
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@18.169.190.18 << 'EOF'
          cd /home/ec2-user/PortfolioCarbonTool
          sudo docker-compose down
          sudo docker-compose up --build -d
          EOF
