# CI/CD конфігурація:
name: Deploy to AWS

on:
  push:
    branches:
      - master  # Тільки для пушів у гілку master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY_OWN }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.137.38 << 'EOF'
            cd /home/ubuntu/PortfolioCarbonTool

            # Pull the latest changes from the master branch
            sudo git pull origin master
            
            # Activate the virtual environment
            source /home/ubuntu/PortfolioCarbonTool/venv/bin/activate

            # Install new dependencies if any
            pip install -r requirements.txt

            # Run collectstatic to gather static files
            # python manage.py collectstatic --noinput

            # Restart Gunicorn service
            sudo systemctl restart gunicorn

            # Optionally: Check the status of the Gunicorn service
            sudo systemctl status gunicorn
          EOF
