name: Deploy to AWS

on:
  push:
    branches:
      - master  # Тільки для пушів у гілку master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@18.169.190.18 << 'EOF'
            cd /home/ec2-user/PortfolioCarbonTool
            git pull origin master  # Оновлюємо код з репозиторія 
            sudo docker stop portfolio-carbon-tool || true  # Зупиняємо старий контейнер
            sudo docker rm portfolio-carbon-tool || true    # Видаляємо старий контейнер
            sudo docker build -t portfolio-carbon-tool .    # Білдимо новий образ
            # Мапимо директорію на хості для збереження бази даних
            sudo docker run -d -p 8000:8000 --name portfolio-carbon-tool \
              -v /home/ec2-user/PortfolioCarbonTool/db.sqlite3:/app/db.sqlite3 \
              portfolio-carbon-tool  # Запускаємо новий контейнер
          EOF
