name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<EC2_PUBLIC_IP> << 'EOF'
            cd /path/to/your/project
            git pull origin main
            sudo docker build -t portfolio-carbon-tool .  # Білдимо образ
            sudo docker stop portfolio-carbon-tool || true  # Зупиняємо старий контейнер
            sudo docker rm portfolio-carbon-tool || true    # Видаляємо старий контейнер
            sudo docker run -d -p 8000:8000 --name portfolio-carbon-tool portfolio-carbon-tool  # Запускаємо новий контейнер
          EOF
